name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Stryker-Mutator
        run: npm run test:mutate

      - name: Chromatic
        run: npm run chromatic
      
